### ISSUE TITLE
Supported plugins for wpdotnet beta

### ISSUE THREAD

**Issue by bfistein** [iolevel/wpdotnet-sdk#13]
## Supported plugins 

The following is a list of plugins used by our beta testers. The check mark indicates that we have tested the plugin, successfully compiled it and briefly tested its functionality.

> Note: caching plugins are not necessary, as wpdotnet has the ASP.NET Core response cache already built in. We also don't foresee the need for security plugins for now (Wordfence etc.).

- [x] Advanced Custom Fields
- [ ] Akismet
- [ ] Alexa Certify
- [ ] All in one security
- [ ] Amazon Pay
- [ ] AMP 
- [ ] Application Insights
- [ ] ARI Adminer
- [ ] Async Javascript
- [x] Auth0 
- [ ] Autooptimizer
- [ ] Backup Buddy // = iThemes? (*Dependency on iThemes sync, which includes this [error](https://github.com/ithemes/iThemes-Security/issues/136) )
- [ ] BackWPup
- [ ] BBPress
- [ ] Beaver Builder
- [ ] BuddyPress
- [x] Carbon Fields (must delete unit tests)
- [x] Classic Editor
- [ ] Cloudflare
- [ ] ~~CMB2~~ (requires edits to the PHP source code)
- [x] CMS Tree Page View
- [x] Contact Form 7
- [x] Cookie Notice for GDPR
- [ ] Datatables
- [x] Disable comments
- [ ] Divi Builder
- [x] Duplicate Post
- [ ] Duplicator
- [x] Easy Google Fonts
- [x] Elementor
- [ ] Embed Press
- [ ] Essential Grid
- [ ] Flickr Album Gallery
- [ ] Formidable Forms
- [x] Google Analytics for Dashboard WP
- [ ] Google Captcha
- [x] Google comments widget
- [x] Gravity Forms
- [ ] Gsuite
- [x] HTML Editor Syntax Highlighter
- [x] Insert Headers and Footers
- [ ] iThemes Security (*Dependency on iThemes sync, which includes this [error](https://github.com/ithemes/iThemes-Security/issues/136) )
- [ ] iThemes Sync (includes this [error](https://github.com/ithemes/iThemes-Security/issues/136) )
- [x] Jetpack
- [ ] LearnPress
- [ ] Members
- [ ] NextGen Gallery (Pro)
- [ ] NextScripts
- [ ] PageBuilder by SiteOrigin
- [ ] Paypal
- [ ] PDF Embedder Premium
- [ ] Permalink Manager Pro
- [ ] Pods
- [x] Post Types Order
- [ ] PPOM custom product
- [x] Q2W3 Fixed Widget
- [ ] Really Simple SSL
- [x] Redirection
- [ ] Search & Filter Pro
- [ ] ~~SG Optimizer~~(will only work on SiteGround hosting provider)
- [x] Simple History (must delete unit test)
- [x] Simple share buttons adder
- [ ] Simple Sitemap
- [x] Slider Revolution
- [x] Smush
- [ ] Stripe
- [x] Timed Content
- [x] TinyMCE Advanced
- [x] Tiny PNG image optimizer (compiles & activates, didn't test further)
- [ ] Toolset Types (contains error that must be removed or fixed by the vendor)
- [ ] TotalPoll Pro
- [ ] Updraft/UpdraftPlus
- [x] Visual Composer / WPBakery
- [ ] What the File
- [x] Widget Options
- [ ] WooCommerce
- [ ] Wordfence
- [ ] WPclever product bundles
- [x] WPClient
- [x] WP Job Manager
- [ ] WP-Optimize
- [ ] WP Fastest Cache
- [x] WP Author Slug
- [ ] WP-PageNavi
- [ ] WP Mail SMTP
- [ ] WP-QUADS
- [ ] WP-Staging
- [ ] WP Optimize
- [ ] W3 Total Cache
- [x] Yoast SEO (dependency on some other plugin and two erroneous classes have to be commented out)
- [ ] zACF Pro

**Comment by davidshq** [comment]
Great list. Wondering why CMB2 has been crossed off?

Might be helpful if the list could be sorted alphabetically, make it easier for us to see the status of plugins important to us and also if any plugins we think are important are missing.

**Comment by diddledan** [comment]
Might this be better moved to a wiki page so that anyone can edit it to mark known good/bad or add new plugins?

**Comment by bfistein** [comment]
Probably a good idea, thanks for the suggestion.

**Comment by bfistein** [comment]
Done, moved this list over to the Wiki, closing this issue.
